"use client";
import "../styles/globals.css";
// app/layout.js
import { Provider } from "react-redux";
import store from "../redux/store/store";
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const handleLogout = () => {
  // Clear authentication data
  localStorage.removeItem("token");
  alert("You have been logged out.");
  router.push("/login"); // Redirect to login page
};

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className="m-0 p-0">
          {children}
        </body>
      </html>
    </Provider>
  );
}
