export const SET_MOVIES_LIST = "SET_MOVIES_LIST";
export const RESET_MOVIES_LIST = "RESET_MOVIES_LIST";

export const SET_SHOWS_LIST = "SET_SHOWS_LIST";
export const RESET_SHOWS_LIST = "RESET_SHOWS_LIST";
